// Browser smoke tests using Chrome's built-in DevTools protocol. No npm packages.
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdir,mkdtemp,readFile,writeFile,readdir} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {resolve} from 'node:path';
const root=resolve(import.meta.dirname,'..');
const qa=resolve(root,'.qa');
await mkdir(qa,{recursive:true});
const profile=await mkdtemp(resolve(qa,'chrome-'));
const downloads=resolve(qa,'downloads');await mkdir(downloads,{recursive:true});
const browserPath=process.env.BROWSER_PATH||['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(existsSync);
if(!browserPath)throw new Error('Set BROWSER_PATH to a local Chrome or Edge executable.');
const port=Number(process.env.TEST_PORT||4175),debugPort=Number(process.env.CDP_PORT||9227);
const server=spawn(process.execPath,['scripts/serve.mjs'],{cwd:root,env:{...process.env,PORT:String(port)},windowsHide:true,stdio:'pipe'});
const chrome=spawn(browserPath,['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
let launchError;chrome.on('error',error=>{launchError=error;});server.on('error',error=>{launchError=error;});
let ws;let nextId=0;const pending=new Map();const events=new Map();const errors=[];let checks=0;
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function waitFor(fn,message,timeout=15000){const end=Date.now()+timeout;let last;while(Date.now()<end){if(launchError)throw launchError;try{const result=await fn();if(result)return result;}catch(error){last=error;}await sleep(80);}throw new Error(`${message}${last?`: ${last.message}`:''}`);}
function send(method,params={}){return new Promise((resolve,reject)=>{const id=++nextId;const timeout=setTimeout(()=>{pending.delete(id);reject(new Error(`CDP timeout: ${method}`));},20000);pending.set(id,{resolve,reject,timeout});ws.send(JSON.stringify({id,method,params}));});}
async function evaluate(expression){const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result.value;}
async function click(selector){await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);}
async function fill(selector,value){await evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));})()`);}
const text=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).textContent`);
const count=selector=>evaluate(`document.querySelectorAll(${JSON.stringify(selector)}).length`);
async function check(name,fn){await fn();checks++;console.log(`PASS ${name}`);}
async function ready(){await waitFor(()=>evaluate(`!!document.querySelector('#shift-date')?.value`),'App did not initialize');}
function onceEvent(method){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{events.delete(method);reject(new Error(`Event timeout: ${method}`));},15000);events.set(method,()=>{clearTimeout(timer);resolve();});});}
async function reload(){const loaded=onceEvent('Page.loadEventFired');await send('Page.reload',{ignoreCache:false});await loaded;await ready();}
async function screenshot(filename){const metrics=await send('Page.getLayoutMetrics');const {data}=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y:0,width:metrics.cssContentSize.width,height:metrics.cssContentSize.height,scale:1}});await writeFile(resolve(qa,filename),Buffer.from(data,'base64'));}
const storageExpression=`'soghica.data.v1:'+new URL('.',location.href).pathname`;
const readStored=()=>evaluate(`JSON.parse(localStorage.getItem(${storageExpression}))`);
try{
  await waitFor(async()=>{const result=await fetch(`http://127.0.0.1:${port}/SoGhiCa/`);return result.ok;},'Test server failed');
  const pages=await waitFor(async()=>{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);const list=await response.json();return list.find(p=>p.type==='page');},'Headless browser failed');
  ws=new WebSocket(pages.webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true});});
  ws.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id){const p=pending.get(message.id);if(p){clearTimeout(p.timeout);pending.delete(message.id);message.error?p.reject(new Error(message.error.message)):p.resolve(message.result);}}const listener=events.get(message.method);if(listener){events.delete(message.method);listener();}if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails.exception?.description||message.params.exceptionDetails.text);});
  await send('Runtime.enable');await send('Page.enable');await send('Network.enable');
  await send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});
  await send('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});
  const loaded=onceEvent('Page.loadEventFired');await send('Page.navigate',{url:`http://localhost:${port}/SoGhiCa/`});await loaded;await ready();
  await check('empty state contains no fabricated earnings',async()=>{assert.equal(await text('#total-income'),'0');assert.equal(await count('.shift-card'),0);});
  await check('PWA precaches every asset under a repository subpath',async()=>{await waitFor(()=>evaluate(`!!navigator.serviceWorker.controller`),'Service worker did not control app');assert.equal(await evaluate(`navigator.serviceWorker.controller.scriptURL`),`http://localhost:${port}/SoGhiCa/sw.js`);const list=await evaluate(`caches.keys().then(async keys=>{const c=await caches.open(keys.find(k=>k.startsWith('soghica-')));return (await c.keys()).map(r=>r.url)})`);assert.equal(list.length,11);assert.ok(list.every(url=>url.includes('/SoGhiCa/')));const manifest=await evaluate(`fetch('./manifest.webmanifest').then(r=>r.json())`);assert.equal(manifest.scope,'./');assert.equal(manifest.start_url,'./');});
  await check('demo view is isolated and totals match its rows',async()=>{await click('#empty-action');assert.equal(await count('.shift-card'),4);assert.equal(await text('#total-income'),'690.000');assert.equal(await readStored(),null);await screenshot('desktop.png');await click('#exit-demo');});
  await check('save overnight shift and persist exact pay',async()=>{await fill('#shift-date','2026-10-06');await fill('#start-time','22:00');await fill('#end-time','02:30');await fill('#shift-tip','30000');assert.equal(await text('#estimated-pay'),'142.500₫');await click('.save-button');assert.equal(await count('.shift-card'),1);assert.equal(await text('#total-income'),'142.500');const data=await readStored();assert.equal(data.shifts[0].minutes,270);await reload();assert.equal((await readStored()).shifts.length,1);});
  await check('edit recalculates and keeps unique record',async()=>{await click('.edit-shift');await fill('#shift-tip','45000');await click('.save-button');assert.equal((await readStored()).shifts.length,1);assert.equal(await text('#total-income'),'157.500');});
  await check('manual hours, multiple shifts per day, and filters',async()=>{await fill('#shift-date','2026-10-06');await click('[data-job="tutor"]');await fill('#manual-hours','2.5');await click('.save-button');assert.equal(await text('#total-income'),'457.500');assert.equal(await text('#total-days'),'1');assert.equal(await text('#total-hours'),'7');await click('[data-filter="tutor"]');assert.equal(await count('.shift-card'),1);assert.equal(await text('#total-income'),'457.500');await click('[data-filter="all"]');});
  await check('month navigation and empty filter state work',async()=>{await click('#previous-month');assert.equal(await count('.shift-card'),0);assert.equal(await text('#total-income'),'0');await click('#next-month');assert.equal(await count('.shift-card'),2);});
  await check('settings change future rates without changing historical wages',async()=>{await click('#open-settings');await fill('#setting-name','Mai Anh');await fill('#setting-cafe-rate','30000');await click('#settings-form .primary-button');assert.equal(await text('#profile-name'),'Mai Anh');assert.equal((await readStored()).shifts.find(s=>s.job==='cafe').rate,25000);assert.equal(await text('#total-income'),'457.500');});
  await check('CSV and JSON backup downloads preserve saved values',async()=>{await click('#export-csv');await click('#backup-shortcut');await click('#export-backup');await waitFor(async()=>(await readdir(downloads)).some(f=>f.endsWith('.json')),'Backup was not downloaded');const files=await readdir(downloads);const json=JSON.parse(await readFile(resolve(downloads,files.find(f=>f.endsWith('.json'))),'utf8'));assert.equal(json.shifts.length,2);assert.ok((await readFile(resolve(downloads,files.find(f=>f.endsWith('.csv'))),'utf8')).includes('157500'));await click('#settings-dialog [data-close-dialog]');});
  await check('cancel deletion preserves record; confirm deletes it',async()=>{await click('.delete-shift');await click('#confirm-cancel');assert.equal(await count('.shift-card'),2);await click('.delete-shift');await click('#confirm-accept');await waitFor(async()=>await count('.shift-card')===1,'Delete failed');assert.equal((await readStored()).shifts.length,1);});
  await check('invalid backup never changes current data',async()=>{await click('#open-settings');await evaluate(`(()=>{const dt=new DataTransfer();dt.items.add(new File(['{"version":1,"shifts":[]}'],'bad.json',{type:'application/json'}));const el=document.querySelector('#backup-file');el.files=dt.files;el.dispatchEvent(new Event('change',{bubbles:true}));})()`);await waitFor(async()=>(await text('#toast')).includes('không hợp lệ'),'Invalid import did not report error');assert.equal((await readStored()).shifts.length,1);await click('#settings-dialog [data-close-dialog]');});
  await check('valid backup requires confirmation and restores all records',async()=>{const files=await readdir(downloads);const backup=await readFile(resolve(downloads,files.find(f=>f.endsWith('.json'))),'utf8');await click('#open-settings');await evaluate(`(()=>{const dt=new DataTransfer();dt.items.add(new File([${JSON.stringify(backup)}],'backup.json',{type:'application/json'}));const el=document.querySelector('#backup-file');el.files=dt.files;el.dispatchEvent(new Event('change',{bubbles:true}));})()`);await waitFor(()=>evaluate(`document.querySelector('#confirm-dialog').open`),'Import confirmation missing');assert.equal((await readStored()).shifts.length,1);await click('#confirm-accept');await waitFor(async()=>(await readStored()).shifts.length===2,'Import did not restore records');});
  await check('stored user text is escaped rather than executed',async()=>{await fill('#shift-date','2026-10-07');await fill('#workplace','<img src=x onerror="window.injected=true">');await click('.save-button');assert.equal(await evaluate('window.injected===true'),false);assert.equal(await count('.shift-card img'),0);assert.ok((await text('#shift-list')).includes('<img src=x'));});
  await check('failed device storage never reports a successful save',async()=>{const before=(await readStored()).shifts.length;await evaluate(`window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('Full','QuotaExceededError')}`);await fill('#shift-date','2026-10-08');await click('.save-button');assert.equal((await readStored()).shifts.length,before);assert.ok((await text('#form-error')).includes('chưa lưu được'));assert.equal(await evaluate(`document.querySelector('#shift-date').value`),'2026-10-08');await evaluate(`Storage.prototype.setItem=window.originalSetItem`);await click('.save-button');});
  await check('offline reload and saving work with the complete cached app',async()=>{await send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await reload();const before=(await readStored()).shifts.length;await fill('#shift-date','2026-10-09');await click('.save-button');assert.equal((await readStored()).shifts.length,before+1);await reload();assert.equal((await readStored()).shifts.length,before+1);await send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});});
  await check('phone, tablet, and desktop widths have no horizontal overflow',async()=>{await click('#open-settings');await click('#show-demo');for(const width of [320,375,390,430,768,1280]){await send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:width<500});assert.equal(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),true,`overflow at ${width}px`);if(width===390){assert.ok(await evaluate(`parseFloat(getComputedStyle(document.querySelector('#workplace')).fontSize)>=16`));await screenshot('iphone.png');}if(width===1280)await screenshot('desktop.png');}});
  await check('install guide, modal close, and touch icon are present',async()=>{await click('#open-install');assert.equal(await evaluate(`document.querySelector('#install-dialog').open`),true);assert.ok((await text('#install-dialog')).includes('Safari'));assert.ok((await text('#offline-status')).includes('sẵn sàng'));await click('#install-dialog [data-close-dialog]');assert.equal(await evaluate(`document.querySelector('#install-dialog').open`),false);assert.equal(await evaluate(`fetch(document.querySelector('link[rel="apple-touch-icon"]').href).then(r=>r.ok)`),true);});
  await check('corrupt data is preserved and saves are blocked',async()=>{await click('#exit-demo');await evaluate(`localStorage.setItem(${storageExpression},'{broken')`);await reload();assert.equal(await evaluate(`document.querySelector('#storage-warning').hidden`),false);await click('.save-button');assert.equal(await evaluate(`localStorage.getItem(${storageExpression})`),'{broken');assert.equal(await evaluate(`document.querySelector('#form-error').hidden`),false);});
  assert.deepEqual(errors,[],'Browser runtime errors');
  console.log(`\n${checks} browser checks passed. Screenshots: .qa/desktop.png and .qa/iphone.png`);
}finally{
  if(ws?.readyState===WebSocket.OPEN){try{await send('Browser.close');}catch{}ws.close();}
  for(const p of pending.values()){clearTimeout(p.timeout);p.reject(new Error('Browser test closed'));}
  chrome.kill();server.kill();
}
