import test from 'node:test';
import assert from 'node:assert/strict';
import {defaults,duration,normalizeTimeInput,endTime,totalPay,validateShift,validateData,summarize,shiftsInMonth,makeCSV,validDate,demoShifts} from '../core.js';
const shift={id:'test-1',date:'2026-10-06',job:'cafe',workplace:'Quán Cafe',start:'22:00',end:'02:30',minutes:270,rate:25000,tip:30000};
test('typed hours normalize without accepting incomplete or impossible times',()=>{
  for(const [input,expected] of [['8','08:00'],['18','18:00'],['830','08:30'],['1830','18:30'],['8:30','08:30'],['00:00','00:00'],['2359','23:59'],[' 9:30 ','09:30']])assert.equal(normalizeTimeInput(input),expected);
  for(const input of ['',null,'9:','8:3','24','24:00','2360','25:30','-1','9pm','12:30x'])assert.equal(normalizeTimeInput(input),null);
  assert.equal(duration(normalizeTimeInput('2330'),normalizeTimeInput('100')),90);
  assert.equal(endTime(normalizeTimeInput('9:30'),1440),'09:30');
  assert.throws(()=>validateShift({...shift,start:'2200'}),'Saved and imported time values remain strict');
});
test('overnight shifts and fractional-hour pay use integer minutes',()=>{assert.equal(duration('22:00','02:30'),270);assert.equal(endTime('22:00',270),'02:30');assert.equal(totalPay(shift),142500);assert.equal(totalPay({...shift,minutes:1,tip:0}),417);assert.equal(duration('14:00','14:00'),0);assert.equal(endTime('14:00',1440),'14:00');});
test('real calendar dates and time bounds are enforced',()=>{assert.equal(validDate('2024-02-29'),true);assert.equal(validDate('2025-02-29'),false);assert.equal(validDate('2026-02-31'),false);assert.equal(validDate('2026-13-01'),false);assert.throws(()=>duration('25:00','00:00'));assert.throws(()=>validateShift({...shift,minutes:0}));assert.throws(()=>validateShift({...shift,minutes:300}));assert.throws(()=>validateShift({...shift,rate:-1}));assert.throws(()=>validateShift({...shift,tip:0.5}));assert.throws(()=>validateShift({...shift,date:'2026-02-30'}));});
test('monthly summary counts days once, sorts and excludes neighboring months',()=>{const entries=[shift,{...shift,id:'test-2',start:'14:00',end:'18:30'},{...shift,id:'test-3',date:'2026-09-30'}];const monthly=shiftsInMonth(entries,'2026-10');const summary=summarize(monthly);assert.equal(monthly.length,2);assert.equal(monthly[0].start,'22:00');assert.equal(summary.dates.size,1);assert.equal(summary.minutes,540);assert.equal(summary.income,285000);});
test('backup validation rejects incomplete, duplicate and unsafe values',()=>{const data={...defaults(),shifts:[shift]};assert.deepEqual(validateData(data),data);assert.throws(()=>validateData({...data,version:2}));assert.throws(()=>validateData({...data,shifts:[shift,shift]}));assert.throws(()=>validateData({...data,profile:null}));assert.throws(()=>validateData({...data,shifts:[{...shift,rate:Infinity}]}));assert.throws(()=>validateData({...data,shifts:[{...shift,id:'<script>'}]}));assert.equal(validateData({...data,shifts:[{...shift,workplace:'<script>alert(1)</script>'}]}).shifts.length,1);});
test('CSV preserves Vietnamese, quotes commas, and neutralizes spreadsheet formulas',()=>{const csv=makeCSV([{...shift,workplace:'=SUM(1,2)'}]);assert.ok(csv.startsWith('\uFEFF'));assert.ok(csv.includes('"\'=SUM(1,2)"'));assert.ok(csv.includes('"142500"'));assert.ok(makeCSV([{...shift,workplace:'Quán "A", B'}]).includes('"Quán ""A"", B"'));});
test('demo totals are derived from four actual rows, independent of user data',()=>{const entries=demoShifts('2026-10');const summary=summarize(entries);assert.equal(summary.income,690000);assert.equal(summary.minutes,1020);assert.equal(summary.dates.size,4);assert.equal(defaults().shifts.length,0);entries.forEach(validateShift);});
